package Vista;

import Controlador.ControladorPrincipal;
import Modelo.GestorUsuarios;
import Modelo.Usuario;

import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.JTextArea;
import javax.swing.JTable;
import java.util.logging.Logger;


public class VentanaPrincipal extends javax.swing.JFrame {

    private GestorUsuarios gestor;
    private ControladorPrincipal controlador;
    private Usuario usuarioActual;

    public VentanaPrincipal() {
        initComponents();
        inicializarAtributos();
    }
    
    private static final Logger logger = Logger.getLogger(VentanaPrincipal.class.getName());
    
    private void inicializarAtributos() {
    
    gestor = new GestorUsuarios();

    usuarioActual = null;
    

    controlador = new ControladorPrincipal(gestor, this);

    txtValorKWh.setText("200");
    txtHabitantes.setText("1");

    txtResultado.setText("""
                         Bienvenido al sistema de Calculo y registro de Consumo Electrico
                         
                         1. Llene los datos del usuario.
                         2. Pulse "Registrar usuario" para calcular y guardar.
                         3. Pulse "Generar reporte" para ver todos los registros.
                         
                         Rangos de clasificacion:
                            Menos de 100 kWh .... Consumo bajo
                            De 100 a 199 kWh .... Consumo moderado
                            De 200 a 299 kWh .... Consumo alto
                            300 kWh o mas ....... Consumo muy alto
                         """);
    actualizarPanelesSegunTipo();
}
    
    
    //Metodo para limpiar los campos al precionar el Boton
    public void limpiarCampos() {

    txtIdentificacion.setText("");
    txtNombre.setText("");
    txtConsumo.setText("");

    txtHabitantes.setText("1");

    txtRubro.setText("");
    txtNit.setText("");

    txtIdentificacion.requestFocus();
}
            
    //Getters and Setters
    public JTextField getTxtIdentificacion() {
    return txtIdentificacion;
}

public JTextField getTxtNombre() {
    return txtNombre;
}

public JComboBox<String> getCboTipoUsuario() {
    return cboTipoUsuario;
}

public JTextField getTxtConsumo() {
    return txtConsumo;
}

public JTextField getTxtValorKWh() {
    return txtValorKWh;
}

public JTextField getTxtHabitantes() {
    return txtHabitantes;
}

public JTextField getTxtRubro() {
    return txtRubro;
}

public JTextField getTxtNit() {
    return txtNit;
}

public JTextArea getTxtResultado() {
    return txtResultado;
}

public JTable getTablaUsuarios() {
    return tablaUsuarios;
}

 // Devuelve el gestor donde estan guardados todos los usuarios. //

public Usuario getUsuarioActual() {
    return usuarioActual;
}

public void setUsuarioActual(Usuario usuarioActual) {
    this.usuarioActual = usuarioActual;
}
    
public void mostrarUsuarioEncontrado(Usuario usuario) {

    txtResultado.setText(
        "=== USUARIO ENCONTRADO ===\n\n"
        + usuario.obtenerDetalles()
    );
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormulario = new javax.swing.JPanel();
        lblIdentificacion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        lblValorKWh = new javax.swing.JLabel();
        lblConsumo = new javax.swing.JLabel();
        cboTipoUsuario = new javax.swing.JComboBox<>();
        txtIdentificacion = new javax.swing.JTextField();
        txtValorKWh = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtConsumo = new javax.swing.JTextField();
        pnlResidencial = new javax.swing.JPanel();
        lblHabitantes = new javax.swing.JLabel();
        txtHabitantes = new javax.swing.JTextField();
        pnlBotones = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        pnlComercial = new javax.swing.JPanel();
        lblRubro = new javax.swing.JLabel();
        txtRubro = new javax.swing.JTextField();
        lblNit = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        pnlResultados = new javax.swing.JPanel();
        splitResultados = new javax.swing.JSplitPane();
        scrollResultado = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        scrollTabla = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del usuario"));

        lblIdentificacion.setText("Identificacion:");

        lblNombre.setText("Nombre de usuario:");

        lblTipoUsuario.setText("Tipo de usuario:");

        lblValorKWh.setText("Valor del Kwh:");

        lblConsumo.setText("Consumo en Kwh:");

        cboTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Residencial", "Comercial" }));
        cboTipoUsuario.addActionListener(this::cboTipoUsuarioActionPerformed);

        txtValorKWh.addActionListener(this::txtValorKWhActionPerformed);

        lblHabitantes.setText("Numero de Habitantes:");

        javax.swing.GroupLayout pnlResidencialLayout = new javax.swing.GroupLayout(pnlResidencial);
        pnlResidencial.setLayout(pnlResidencialLayout);
        pnlResidencialLayout.setHorizontalGroup(
            pnlResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResidencialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlResidencialLayout.setVerticalGroup(
            pnlResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResidencialLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pnlResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHabitantes)
                    .addComponent(txtHabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnRegistrar.setText("Registrar usuario");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnBuscar.setText("Buscar por Identificacion");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnReporte.setText("Generar Reporte");
        btnReporte.addActionListener(this::btnReporteActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addGap(35, 35, 35)
                .addComponent(btnReporte)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addGap(54, 54, 54))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnRegistrar)
                    .addComponent(btnReporte)
                    .addComponent(btnLimpiar))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pnlComercial.setToolTipText("");
        pnlComercial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlComercial.setPreferredSize(new java.awt.Dimension(653, 41));

        lblRubro.setText("Tipo de Negocio:");

        lblNit.setText("NIT:");

        javax.swing.GroupLayout pnlComercialLayout = new javax.swing.GroupLayout(pnlComercial);
        pnlComercial.setLayout(pnlComercialLayout);
        pnlComercialLayout.setHorizontalGroup(
            pnlComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComercialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblNit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pnlComercialLayout.setVerticalGroup(
            pnlComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComercialLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRubro)
                    .addComponent(txtRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNit)
                    .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createSequentialGroup()
                .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2165, 2165, 2165))
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormularioLayout.createSequentialGroup()
                                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblTipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblIdentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(txtValorKWh, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(lblValorKWh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(txtConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnlResidencial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlComercial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificacion)
                    .addComponent(lblNombre)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoUsuario)
                    .addComponent(lblConsumo)
                    .addComponent(cboTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorKWh)
                    .addComponent(txtValorKWh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        splitResultados.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitResultados.setResizeWeight(0.6);
        splitResultados.setLastDividerLocation(200);
        splitResultados.setPreferredSize(new java.awt.Dimension(98, 51));

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        scrollResultado.setViewportView(txtResultado);

        splitResultados.setTopComponent(scrollResultado);

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTabla.setViewportView(tablaUsuarios);

        splitResultados.setRightComponent(scrollTabla);

        javax.swing.GroupLayout pnlResultadosLayout = new javax.swing.GroupLayout(pnlResultados);
        pnlResultados.setLayout(pnlResultadosLayout);
        pnlResultadosLayout.setHorizontalGroup(
            pnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlResultadosLayout.setVerticalGroup(
            pnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        controlador.generarReporte();
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        controlador.buscarUsuario(
            txtIdentificacion.getText()
        );
    }//GEN-LAST:event_btnBuscarActionPerformed

    //Accion de los 4 botones
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        controlador.registrarUsuario();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtValorKWhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorKWhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorKWhActionPerformed

    private void cboTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoUsuarioActionPerformed
        actualizarPanelesSegunTipo();        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoUsuarioActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JComboBox<String> cboTipoUsuario;
    private javax.swing.JLabel lblConsumo;
    private javax.swing.JLabel lblHabitantes;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRubro;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JLabel lblValorKWh;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlComercial;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlResidencial;
    private javax.swing.JPanel pnlResultados;
    private javax.swing.JScrollPane scrollResultado;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JSplitPane splitResultados;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtConsumo;
    private javax.swing.JTextField txtHabitantes;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtRubro;
    private javax.swing.JTextField txtValorKWh;
    // End of variables declaration//GEN-END:variables

    private void actualizarPanelesSegunTipo() {
    String tipo = (String) cboTipoUsuario.getSelectedItem();
    
    if (tipo == null) return;
    
    boolean esResidencial = tipo.equalsIgnoreCase("Residencial");
    
    pnlResidencial.setVisible(esResidencial);
    pnlComercial.setVisible(!esResidencial);
    
    // Opcional: refrescar el layout del contenedor padre
    if (pnlResidencial.getParent() != null) {
        pnlResidencial.getParent().revalidate();
        pnlResidencial.getParent().repaint();
    }
}

   
    
    
    
}
